services:

  redis:
    image: redis:latest

  scaphandre:
    image: docker.io/hubblo/scaphandre
    command: prometheus -p 8080 -a 0.0.0.0
    privileged: true  # Required for hardware access
    security_opt:
      - apparmor=unconfined
    network_mode: "host"
    volumes:
      - /sys/class/powercap:/sys/class/powercap  # RAPL power metrics
      - /proc:/proc  # Process information
    restart: unless-stopped

  proxy:
    build: .
    ports:
      - 8676:8676
    depends_on:
      - metadata-service
      - backend
    environment:
      - DATACLAY_PROXY_MDS_HOST=metadata-service
      - DATACLAY_KV_HOST=redis
    command: python -m dataclay.proxy

  metadata-service:
    build: .
    depends_on:
      - redis
    environment:
      - DATACLAY_KV_HOST=redis
    command: python -m dataclay.metadata

  backend:
    build: .
    depends_on:
      - redis
    environment:
      - DATACLAY_KV_HOST=redis
      - DATACLAY_MEMORY_CHECK_INTERVAL=600
    command: python -m dataclay.backend
    volumes:
      - ./model:/usr/src/model:ro

  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    command: --config=/etc/otel-config.yaml
    network_mode: host
    depends_on:
      - scaphandre

  bridge-config:
    build:
      context: .
      dockerfile: bridge-config.Dockerfile
    depends_on:
      - proxy
      - metadata-service
      - backend
      - redis
    environment:
      - DATACLAY_PROXY_HOST=proxy
      - DATACLAY_PROXY_PORT=8676
    restart: on-failure

  bridge:
    build:
      context: .
      dockerfile: bridge.Dockerfile
    network_mode: host
    depends_on:
      - bridge-config
      - otel-collector
      - scaphandre
    environment:
      - DATACLAY_PROXY_HOST=localhost
      - DATACLAY_PROXY_PORT=8676
    restart: on-failure

